### ISSUE TITLE
Typo in setup.py

### ISSUE THREAD

**Issue by plachert** [ArjanCodes/2023-package#2]
There seems to be a typo, that results in the following error when trying to install the package:
```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-7lljaf_d/setup.py", line 3, in <module>
          with open("app/Readme.md", "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'app/Readme.md
```
      
Renaming either the `README.md` or the reference in `setup.py` should resolve the issue.

PS: Thanks for a great YT channel. I have learnt a lot. Keep up the good work :)

**Comment by egges** [comment]
Thanks for noting that - it's fixed!
